import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./component/Navbar";
import { Poppins } from "next/font/google";
import Footer from "./component/Footer";
const poppins = Poppins({
  weight: ['400', '600', '700'], // regular, semi-bold, bold
  subsets: ['latin'],
  display: 'swap'
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">

      <body
        className={poppins.className}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
